# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pvectl < Formula
  desc "CLI for managing a Proxmox VE cluster over the REST API"
  homepage "https://github.com/davegallant/homebrew-public"
  version "0.1.0-rc1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/davegallant/pvectl/releases/download/v0.1.0-rc1/pvectl_0.1.0-rc1_darwin_amd64.tar.gz"
      sha256 "47ac4cf415999941c9310ec16f16d2dc4e7db2f2193d4403d687d0644a1aa4f5"

      define_method(:install) do
        bin.install "pvectl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/davegallant/pvectl/releases/download/v0.1.0-rc1/pvectl_0.1.0-rc1_darwin_arm64.tar.gz"
      sha256 "99825437baae4f25106a9a03284c0c1c016a905c77dabf9aea09b475e1ffea5d"

      define_method(:install) do
        bin.install "pvectl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/davegallant/pvectl/releases/download/v0.1.0-rc1/pvectl_0.1.0-rc1_linux_amd64.tar.gz"
      sha256 "bf2ae9ddb7ff07d6081b1b10a64f559f194604b2fe4a2c4822d1514981f42adb"
      define_method(:install) do
        bin.install "pvectl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/davegallant/pvectl/releases/download/v0.1.0-rc1/pvectl_0.1.0-rc1_linux_arm64.tar.gz"
      sha256 "97c4228623c9c8ffb94180d17e76d50dbe79c221abc7ec4155170de500bef30c"
      define_method(:install) do
        bin.install "pvectl"
      end
    end
  end
end
