# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vpngate < Formula
  desc "a client for vpngate.net"
  homepage "https://github.com/davegallant/homebrew-public"
  version "0.1.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/davegallant/vpngate/releases/download/v0.1.0/vpngate_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "0b05e78c68d627137ee31de5a6f5be5ade08cb74fa819798f4671ee634311098"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/davegallant/vpngate/releases/download/v0.1.0/vpngate_0.1.0_Linux_x86_64.tar.gz"
      sha256 "8149cce65e4e658df1774f2d88b034daf70d95978700cfed9597010778d1017a"
    end
  end

  def install
    bin.install "vpngate"
  end
end
