# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vpngate < Formula
  desc "a client for vpngate.net"
  homepage "https://github.com/davegallant/homebrew-public"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/davegallant/vpngate/releases/download/v0.4.0/vpngate_0.4.0_darwin_amd64.tar.gz"
      sha256 "7d857b4c588744db90fc957d425730614d0e436bb554a7f97329aac101926e43"

      define_method(:install) do
        bin.install "vpngate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/davegallant/vpngate/releases/download/v0.4.0/vpngate_0.4.0_darwin_arm64.tar.gz"
      sha256 "199cd052fe974c3d3839d114e731efa49e09bf5c91d2afe930c7322ca738314e"

      define_method(:install) do
        bin.install "vpngate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/davegallant/vpngate/releases/download/v0.4.0/vpngate_0.4.0_linux_amd64.tar.gz"
      sha256 "c2ed03eb0f0f77a851b3f345146c02fb6f18d0caef284e4cd62dc1051a7b7c5f"
      define_method(:install) do
        bin.install "vpngate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/davegallant/vpngate/releases/download/v0.4.0/vpngate_0.4.0_linux_arm64.tar.gz"
      sha256 "bc67337981f178cd15fbde501d872c0d60cb1662478fe146926d1a311a6ba91d"
      define_method(:install) do
        bin.install "vpngate"
      end
    end
  end
end
