# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vpngate < Formula
  desc "a client for vpngate.net"
  homepage "https://github.com/davegallant/homebrew-public"
  version "0.3.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/davegallant/vpngate/releases/download/v0.3.5/vpngate_0.3.5_darwin_amd64.tar.gz"
      sha256 "09c354e24db2dae57586bfd28aa6009c25e2053b1d1a39080aff46b901966cb6"

      def install
        bin.install "vpngate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/davegallant/vpngate/releases/download/v0.3.5/vpngate_0.3.5_darwin_arm64.tar.gz"
      sha256 "fb674dc47f3546181b29cd2280a73da5eefed3d0ac04abbe1e7d877a03805e90"

      def install
        bin.install "vpngate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/davegallant/vpngate/releases/download/v0.3.5/vpngate_0.3.5_linux_amd64.tar.gz"
      sha256 "1a5ee39f37cbf3b224b78fe6c9c4beba03a888b4971445836de79aed5d4bdbfd"
      def install
        bin.install "vpngate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/davegallant/vpngate/releases/download/v0.3.5/vpngate_0.3.5_linux_arm64.tar.gz"
      sha256 "0929ececc78aebe77525c86fad6c3f0517a43253a148cc6547ffdb45ba3fdb5b"
      def install
        bin.install "vpngate"
      end
    end
  end
end
